auth0.domain=dev-rp3cq3s4ynegwlw7.us.auth0.com
auth0.clientId=TV4hXvMlAX84w9hyc5bDiay96cQPVLt6
auth0.audience=https://api.hoodly.fr
auth0.redirectUri=http://localhost:3001/callback
api.baseUrl=https://api.hoodly.fr
